### ISSUE TITLE
Add docker image?

### ISSUE THREAD

**Issue by mlissner** [juggernaut/webhook-sentry#4]
Hello, we're working on setting up webhooks at CourtListener.com and thinking about using this tool.

Our infrastructure is in k8s, which means that we need things like this to be dockerized. Putting this in a docker image is fairly easy, but I'm curious if the maintainers here would welcome a PR with that enhancement? 

I think we'd just create a `Dockerfile` in the root of the repo and then maybe add something to `release.yml` so that the docker file is pushed to Docker Hub as part of each release. (If we do the auto-release thing, we'll need help from somebody to get docker hub credentials set up in Github.)

We're still analyzing webhook proxies, but if we wind up going this direction would something like this be helpful/welcome?

**Comment by juggernaut** [comment]
Hello @mlissner , thanks for bringing up Docker support. It would absolutely be welcome -- in fact, I was going to get around to doing this myself since I've been working on containerizing my personal projects (one of which uses webhook-sentry).

Understand you're still evaluating webhook proxies, but I'd be glad to help if you need any help/support with webhook-sentry.

**Comment by mlissner** [comment]
Great to hear it! We'll be getting to this pretty soon, I think and I'm sure we'll have more questions when we do (unless we go another direction, which could totally happen, but hearing your support here really makes this look like an appealing option). Thanks for making this great proxy.
